# Generated by Django 5.2.6 on 2025-09-26 23:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('owner'), name='unique_label_per_user_case_insensitive'),
        ),
    ]
