# Generated by Django 5.2.6 on 2025-09-20 23:25

import django.db.models.deletion
import notes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('title',), 'verbose_name': 'метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'default_related_name': 'notes', 'verbose_name': 'заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.RemoveField(
            model_name='label',
            name='author',
        ),
        migrations.AddField(
            model_name='label',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL, verbose_name='владелец метки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(help_text='название метки', max_length=64, validators=[notes.validators.validate_title], verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['owner'], name='notes_label_owner_i_c75ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['author', 'created_at'], name='notes_note_author__c491a7_idx'),
        ),
    ]
